name: Build pull requests

on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: make install.env
    - name: Build
      run: make build
