name: Publish to octopus

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: make install.ci
    - name: Publish packages
      run: make publish NUGET_API_KEY=${{ secrets.NUGET_API_KEY }}
